### ISSUE TITLE
search is inflexible with non-ascii characters.

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/censusreporter#190]
In testing #189 I found that you get different results searching for 
http://censusreporter.org/search-results/?q=canon
or
http://censusreporter.org/search-results/?q=ca%C3%B1on

I think we should assume most folks won't type diacriticals, so ideally, searching for _canon_ would also return results which match _cañon_

**Comment by tuchandra** [comment]
This is probably a config setting somewhere on the postgres side, with how it builds / parses the documents. I can check it out tomorrow.

**Comment by iandees** [comment]
See also #189 and https://app.getsentry.com/share/issue/36363939342e313530333833363131/.

**Comment by iandees** [comment]
This is happening because the [search URL is being built as a `str`, not a `unicode`](https://github.com/censusreporter/censusreporter/blob/master/censusreporter/apps/census/views.py#L831).

**Comment by JoeGermuska** [comment]
@iandees I actually fixed those -- because I'm not 100% sure that we should assume that all browers can handle unicode URLs -- but that's what led me to find this bug.

**Comment by iandees** [comment]
@JoeGermuska is that fix pushed to GitHub? Doesn't look like it's fixed.

**Comment by JoeGermuska** [comment]
If both of these URLs work

http://censusreporter.org/search-results/?q=canon
http://censusreporter.org/search-results/?q=ca%C3%B1on

what isn't fixed?

**Comment by iandees** [comment]
I'm not questioning if the website is fixed, I'm just wondering where the code is? What branch of this repo is deployed?

**Comment by iandees** [comment]
I see, you closed https://github.com/censusreporter/censusreporter/issues/189 in ad5e056b.

Can we close this issue, too?

**Comment by JoeGermuska** [comment]
This issue is not ready to be closed. It won't be until

http://censusreporter.org/search-results/?q=canon
http://censusreporter.org/search-results/?q=ca%C3%B1on

return identical results (as well as all the other cases where we can expect that naive searchers won't know to type accents or tildes)

Since our corpus is finite and only changes annually, we could in a pinch handle all of them in a dictionary file.

I posted [a question to the DBA stack exchange](
http://dba.stackexchange.com/questions/148020/supporting-non-ascii-characters-in-postgres-full-text-english) to see if there's a built-in way to do it.

(just to stash it, since I haven't yet internalized the awesome regex syntax postgres supports, here's a way to get all of the place names affected by this, although we omit `067` from the full text index)

```sql
select sumlevel, count(*) 
from tiger2014.census_name_lookup 
where display_name ~ '[^[:ascii:]]' 
group by sumlevel 
order by sumlevel;

 sumlevel | count 
----------+-------
 050      |    17
 060      |   332
 067      |    22
 140      |   257
 150      |   672
 160      |    68
 251      |     2
 310      |     4
 330      |     2
 400      |     6
 795      |    14
 970      |     4
```

**Comment by iandees** [comment]
This would probably help: https://www.postgresql.org/docs/9.0/static/unaccent.html

**Comment by JoeGermuska** [comment]
yeah, that looks good. but we should make sure it doesn't penalize people who type them in correctly. Maybe we 'unaccent' queries as well before putting them into the search.

**Comment by JoeGermuska** [comment]
@Joonpark13 this is something we should be resolving as part of wrapping up search

**Comment by JoeGermuska** [comment]
This continues to be an issue -- people who don't know to type in diacriticals will probably be confused. URLs above are obsolete, but these demonstrate the issue:

https://censusreporter.org/search/?q=canon
https://censusreporter.org/search/?q=ca%C3%B1on
